In [ ]:
import pandas as pd
import torch
import numpy as np
import cv2

In [ ]:
print(torch.__version__)

2.9.0+cu126


In [ ]:
!nvidia-smi

Thu Dec 11 10:41:40 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   49C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

# **creating tensors**

## **scalar**

In [ ]:
scalar=torch.tensor(8)

In [ ]:
dir(scalar)

['H',
 'T',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__red

In [ ]:
scalar.ndim

0

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
"""code to convert tensor into python obj back"""
scalar.item()

8

## **vector**

In [ ]:
vector=torch.tensor([23,43])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

## **Matrix**

In [ ]:
MATRIX=torch.tensor([[1,2],[1,3]])

In [ ]:
MATRIX

tensor([[1, 2],
        [1, 3]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1][1]

tensor(3)

In [ ]:
MATRIX1=torch.tensor([[3,2],[6,3]])

In [ ]:
MATRIX1

tensor([[3, 2],
        [6, 3]])

In [ ]:
MATRIX1.shape,MATRIX.shape

(torch.Size([2, 2]), torch.Size([2, 2]))

In [ ]:
MATRIX1

tensor([[3, 2],
        [6, 3]])

In [ ]:
MATRIX1[1][1].item()

3

## **TENSOR**

In [ ]:
SIMPLE_TENSOR=torch.tensor([[[1,2,3],
                              [2,3,4],
                              [3,4,5]]])

In [ ]:
SIMPLE_TENSOR

tensor([[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]]])

In [ ]:
SIMPLE_TENSOR.ndim

3

In [ ]:
SIMPLE_TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
COMPLEX_TENSOR=torch.tensor([[[1,2,3],
                              [2,3,4],
                              [3,4,5]],[[10,20,30],
                              [20,30,40],
                              [30,40,50]]])

In [ ]:
COMPLEX_TENSOR

tensor([[[ 1,  2,  3],
         [ 2,  3,  4],
         [ 3,  4,  5]],

        [[10, 20, 30],
         [20, 30, 40],
         [30, 40, 50]]])

In [ ]:
COMPLEX_TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
COMPLEX_TENSOR[1][2][2].item()

50

In [ ]:
COMPLEX_TENSOR.ndim

3

## **Random tensors**
random tensors are important because a neural network starts with random numbers and then adjust to better reperesent the data

In [ ]:
#random tensor creation of size(x,x)

random_tensor=torch.rand(10,3,4)


In [ ]:
random_tensor

tensor([[[0.5765, 0.4348, 0.8041, 0.1629],
         [0.6066, 0.2600, 0.9891, 0.2740],
         [0.3908, 0.5972, 0.8334, 0.7197]],

        [[0.3567, 0.5044, 0.3704, 0.3559],
         [0.8819, 0.4409, 0.1782, 0.9396],
         [0.2936, 0.4291, 0.5284, 0.8701]],

        [[0.8827, 0.2178, 0.8204, 0.7526],
         [0.0783, 0.2056, 0.2458, 0.5283],
         [0.2116, 0.2383, 0.9649, 0.4065]],

        [[0.5268, 0.0232, 0.8297, 0.9376],
         [0.6243, 0.9576, 0.9755, 0.3868],
         [0.3838, 0.5458, 0.6190, 0.6039]],

        [[0.5782, 0.5934, 0.0156, 0.8505],
         [0.1509, 0.0921, 0.3016, 0.3529],
         [0.5542, 0.8042, 0.8964, 0.2965]],

        [[0.6739, 0.3626, 0.6071, 0.5766],
         [0.7844, 0.6091, 0.7051, 0.8266],
         [0.6808, 0.0184, 0.3732, 0.3349]],

        [[0.5236, 0.3729, 0.5549, 0.7605],
         [0.1842, 0.3275, 0.0949, 0.3140],
         [0.7593, 0.4723, 0.2300, 0.5901]],

        [[0.9123, 0.8939, 0.6713, 0.6830],
         [0.9862, 0.5372, 0.3696, 0.5710

In [ ]:
random_tensor.ndim

3

## **Image Tensor**

In [ ]:
# creating a tensor whose size is similar to image


In [ ]:
img_tensor=torch.rand(size=(224,224,3))

In [ ]:
img_tensor.ndim,img_tensor.shape

(3, torch.Size([224, 224, 3]))

In [ ]:
224*224*3


150528

### **Zeros and Ones**

In [ ]:
zero_tensor=torch.zeros(10,3,4)

In [ ]:
zero_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
zero_tensor*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
ones_tensor=torch.ones(10,3,4)

In [ ]:
ones_tensor

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
ones_tensor*random_tensor

tensor([[[0.5765, 0.4348, 0.8041, 0.1629],
         [0.6066, 0.2600, 0.9891, 0.2740],
         [0.3908, 0.5972, 0.8334, 0.7197]],

        [[0.3567, 0.5044, 0.3704, 0.3559],
         [0.8819, 0.4409, 0.1782, 0.9396],
         [0.2936, 0.4291, 0.5284, 0.8701]],

        [[0.8827, 0.2178, 0.8204, 0.7526],
         [0.0783, 0.2056, 0.2458, 0.5283],
         [0.2116, 0.2383, 0.9649, 0.4065]],

        [[0.5268, 0.0232, 0.8297, 0.9376],
         [0.6243, 0.9576, 0.9755, 0.3868],
         [0.3838, 0.5458, 0.6190, 0.6039]],

        [[0.5782, 0.5934, 0.0156, 0.8505],
         [0.1509, 0.0921, 0.3016, 0.3529],
         [0.5542, 0.8042, 0.8964, 0.2965]],

        [[0.6739, 0.3626, 0.6071, 0.5766],
         [0.7844, 0.6091, 0.7051, 0.8266],
         [0.6808, 0.0184, 0.3732, 0.3349]],

        [[0.5236, 0.3729, 0.5549, 0.7605],
         [0.1842, 0.3275, 0.0949, 0.3140],
         [0.7593, 0.4723, 0.2300, 0.5901]],

        [[0.9123, 0.8939, 0.6713, 0.6830],
         [0.9862, 0.5372, 0.3696, 0.5710

In [ ]:
example=torch.rand(3,4)

In [ ]:
zer0_example=torch.zeros(1,4)

In [ ]:
zer0_example,example

(tensor([[0., 0., 0., 0.]]),
 tensor([[0.1989, 0.6648, 0.3970, 0.1073],
         [0.5040, 0.9780, 0.2156, 0.2060],
         [0.4178, 0.6987, 0.2625, 0.6157]]))

In [ ]:
example*zer0_example

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## **Creating a range of tensors and tensor-like**

In [ ]:
twenty_tensor=torch.arange(start=1,end=20)
twenty_tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19])

In [ ]:
# creating a tensor like
twenty_zeros=torch.zeros_like(input=twenty_tensor)
twenty_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
twenty_ones=torch.ones_like(input=twenty_tensor)
twenty_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## **Tensor dtypes**

In [ ]:
tensie_32fl=torch.rand(size=(2,3),dtype=None,device=None,requires_grad=False)

In [ ]:
tensie_16fl=torch.rand(size=(2,3),dtype=torch.float16,device="cuda",requires_grad=False)

In [ ]:
tensie_16fl.shape,tensie_32fl.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [ ]:
print(f"the shape of tensor:{tensie_16fl.shape}")
print(f"the dtype of tensor:{tensie_16fl.dtype}")
print(f"the tensor is on :{tensie_16fl.device}")

the shape of tensor:torch.Size([2, 3])
the dtype of tensor:torch.float16
the tensor is on :cuda:0


In [ ]:
print(f"the shape of tensor:{tensie_32fl.shape}")
print(f"the dtype of tensor:{tensie_32fl.dtype}")
print(f"the tensor is on :{tensie_32fl.device}")

the shape of tensor:torch.Size([2, 3])
the dtype of tensor:torch.float32
the tensor is on :cpu


In [ ]:
tensie_16fl,tensie_32fl

(tensor([[0.4663, 0.1565, 0.7397],
         [0.7026, 0.2240, 0.2296]], device='cuda:0', dtype=torch.float16),
 tensor([[0.5311, 0.7114, 0.8182],
         [0.4005, 0.0841, 0.9089]]))

In [ ]:
tensie_32fl.size()

torch.Size([2, 3])

## **Tensor operations** (manipulation)
 * Addition
 * subtraction
 * multiplication (element wise)
 * division
 * matrix_multipliction

In [ ]:
## create tensor
tensor=torch.tensor([1,2,3])

In [ ]:
## addition
tensor+10

tensor([11, 12, 13])

In [ ]:
## multiplication
tensor*10

tensor([10, 20, 30])

In [ ]:
## subtraction
tensor-10

tensor([-9, -8, -7])

In [ ]:
## built in torch method
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
%%time
## matrix multiplication
torch.matmul(tensor.type(torch.long),torch.tensor([1,2,3],dtype=torch.long))

CPU times: user 1.07 ms, sys: 10 µs, total: 1.08 ms
Wall time: 9.61 ms


tensor(14)

In [ ]:
%%time
val=0
for i in range(len(tensor)):
  val+=tensor[i]*tensor[i]

CPU times: user 797 µs, sys: 0 ns, total: 797 µs
Wall time: 1.03 ms


In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor_b=torch.rand(2,3)
tensor_b

tensor([[0.9539, 0.7792, 0.6357],
        [0.0614, 0.8795, 0.3089]])

In [ ]:
tensor_b.T

tensor([[0.9539, 0.0614],
        [0.7792, 0.8795],
        [0.6357, 0.3089]])

In [ ]:
tensor_b @ tensor_b ##it won't work because of the inner dimension missmatch

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [ ]:
tensor_b @ tensor_b.T

tensor([[1.9212, 0.9403],
        [0.9403, 0.8727]])

## **Tensor aggregation**

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor.min()

tensor(1)

In [ ]:
tensor.max()

tensor(3)

In [ ]:
tensor.type(torch.float32).mean()

tensor(2.)

In [ ]:
tensor.sum()

tensor(6)

In [ ]:
tensor.argmax()

tensor(2)

In [ ]:
tensor.argmin()

tensor(0)

In [ ]:
tensor.argsort()

tensor([0, 1, 2])

## **Reshape, view,squeeze,unsqueeze**

In [ ]:
tensor_b.shape

torch.Size([2, 3])

In [ ]:
tensor_b.reshape(1,6)

tensor([[0.9539, 0.7792, 0.6357, 0.0614, 0.8795, 0.3089]])

In [ ]:
tensor_a=tensor_b.view(dtype=torch.float32)

In [ ]:
tensor_a=tensor_a.reshape(1,6)

In [ ]:
tensor_b

tensor([[0.9539, 0.7792, 0.6357],
        [0.0614, 0.8795, 0.3089]])

### **Stacking**

In [ ]:
torch.stack([tensor,tensor],dim=0)

tensor([[1, 2, 3],
        [1, 2, 3]])

In [ ]:
torch.vstack([tensor,tensor])

tensor([[1, 2, 3],
        [1, 2, 3]])

### **Squeeze and unsqueeze**

In [ ]:
tensor12=torch.randn(224,224,3)

In [ ]:
tensor12.permute(2,0,1).shape


torch.Size([3, 224, 224])

In [ ]:
tensor13=torch.rand(1,2,3,4)

In [ ]:
tensor13.squeeze().shape

torch.Size([2, 3, 4])

In [ ]:
tensor13=tensor13.squeeze()

In [ ]:
tensor12.flatten().shape

torch.Size([150528])

In [ ]:
torch.manual_seed(42)

In [ ]:
tensor11=torch.rand(3,3)
tensor11

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

In [ ]:
tensor11[0][:]

tensor([0.8823, 0.9150, 0.3829])

In [ ]:
tensor11[:,0]

tensor([0.8823, 0.9593, 0.2566])

In [ ]:
import torch

x = torch.tensor([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])


In [ ]:
x

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

In [ ]:
x[:,0]

tensor([10, 40, 70])